package com.example.demo.entity;

import java.io.Serializable;

import lombok.Data;

@Data
public class Bookinfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bookinfo.isbn
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	private String isbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bookinfo.title
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bookinfo.price
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	private Integer price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bookinfo.isbn
	 * @return  the value of bookinfo.isbn
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	public String getIsbn() {
		return isbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bookinfo.isbn
	 * @param isbn  the value for bookinfo.isbn
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	public void setIsbn(String isbn) {
		this.isbn = isbn == null ? null : isbn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bookinfo.title
	 * @return  the value of bookinfo.title
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bookinfo.title
	 * @param title  the value for bookinfo.title
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bookinfo.price
	 * @return  the value of bookinfo.price
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bookinfo.price
	 * @param price  the value for bookinfo.price
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}
}