package com.example.demo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.example.demo.entity.Bookinfo;

@Mapper
public interface BookinfoMapper {

    List<Bookinfo> findAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bookinfo
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	int deleteByPrimaryKey(String isbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bookinfo
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	int insert(Bookinfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bookinfo
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	int insertSelective(Bookinfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bookinfo
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	Bookinfo selectByPrimaryKey(String isbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bookinfo
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	int updateByPrimaryKeySelective(Bookinfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bookinfo
	 * @mbg.generated  Fri Sep 06 18:09:39 JST 2024
	 */
	int updateByPrimaryKey(Bookinfo row);
}